@host = http://localhost:4400

###

GET {{host}}/api/pets

###

POST {{host}}/api/pets
Content-Type: application/json

{"name": "Fluffy", "age": 5, "weightInKg": 7, "kind_id": 1}

###

PATCH  {{host}}/api/pets/31
Content-Type: application/json

{
    "name": "UpdatedPet",
    "age": 50,
    "weightInKg": 10
}

###

GET {{host}}/api/owners

###

POST {{host}}/api/owners
Content-Type: application/json

{"name": "John", "age": 25}

###

GET {{host}}/api/pet-kinds

###